version: '3'
services:

  validator:
    build:
      dockerfile: validator/Dockerfile
    ports:
      - 3334:3334
    restart: unless-stopped  
    command: ["go", "run", "validator/validation.go"]
    volumes:
      - myapp:/home/
    environment:
      - PORT=3334
      - PATH_LOG=../logs.log
    depends_on:
      - postgres
  
  db:
    build:
      dockerfile: db/Dockerfile
    ports:
      - 3335:3335
    restart: unless-stopped  
    command: ["go", "run", "db/database.go"]
    volumes:
      - myapp:/home/
    environment:
      - PORT=3335
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user
      - PATH_LOG=../logs.log
    depends_on:
      - postgres
  
  web:
    build:
      dockerfile: web/Dockerfile
    ports:
      - 3336:3336
    restart: unless-stopped  
    command: ["go", "run", "web/web.go"]
    volumes:
      - myapp:/home/
    environment:
      - PORT=3336
      - PATH_LOG=../logs.log
    depends_on:
      - postgres
  
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user
    ports:
      - "5432:5432"


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - postgres

volumes:
  myapp: